os: windows
language: shell
before_install:
  - choco install python --version=3.9
  - python -m pip install --upgrade pip
env: PATH=/c/Python39:/c/Python39/Scripts:$PATH
install:
  - pip install https://github.com/pyinstaller/pyinstaller/archive/develop.tar.gz
  - pip install -r requirements.txt
script:
  - bash -c echo "Tests would go here"
before_deploy:
  - pyinstaller "main.spec"
deploy:
  provider: releases
  api_key: $RELEASE_TOKEN
  file_glob: true
  file: dist/*.exe
  skip_cleanup: true
  draft: false
  on:
    tags: true
  name: $TRAVIS_TAG